### ISSUE TITLE
Tree

### ISSUE THREAD

**Issue by techniq** [techniq/layerchart#24]
## TODO

- [ ] Improve transitions
  - [ ] Transition children from parent
    - See [AnimatedNodes](https://github.com/techniq/vx-hierarchy-examples/blob/master/src/examples/AnimatedNodes.tsx) and [AnimatedLinks](https://github.com/techniq/vx-hierarchy-examples/blob/master/src/examples/AnimatedLinks.tsx)
- [ ] Improve step curve
  - [ ] Fix with vertical orientation
  - [ ] Support specifying step percentage
    - [ ] Create [custom curve](https://github.com/d3/d3-shape#custom-curves) similar to [LinkHorizontalStep](https://github.com/airbnb/visx/blob/master/packages/visx-shape/src/shapes/link/step/LinkHorizontalStep.tsx).  See [d3-shape's step](https://github.com/d3/d3-shape/blob/main/src/curve/step.js) and class-based [Bump](https://github.com/d3/d3-shape/blob/main/src/curve/bump.js)
- [ ] Support radial layout
